module.exports = {
    invoice: {
        id: 'in_1JUovyHPCO7LDipnKr5tYfV0',
        object: 'invoice',
        account_country: 'PL',
        account_name: 'Stowarzyszenie Otwarte Klatki',
        account_tax_ids: null,
        amount_due: 1000,
        amount_paid: 0,
        amount_remaining: 1000,
        application_fee_amount: null,
        attempt_count: 0,
        attempted: false,
        auto_advance: true,
        automatic_tax: {
            enabled: false,
            status: null,
        },
        billing_reason: 'manual',
        charge: null,
        collection_method: 'charge_automatically',
        created: 1630485398,
        currency: 'pln',
        custom_fields: null,
        customer: 'cus_Jt6DyXJc9c5CMH',
        customer_address: null,
        customer_email: 'max.harris@opencages.org',
        customer_name: 'max',
        customer_phone: null,
        customer_shipping: null,
        customer_tax_exempt: 'none',
        customer_tax_ids: [],
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [],
        description: null,
        discount: null,
        discounts: [],
        due_date: null,
        ending_balance: null,
        footer: null,
        hosted_invoice_url: null,
        invoice_pdf: null,
        last_finalization_error: null,
        lines: {
            object: 'list',
            data: [
                {
                    id: 'il_1JUovyHPCO7LDipnrnSv3x1t',
                    object: 'line_item',
                    amount: 1000,
                    currency: 'pln',
                    description: 'My First Invoice Item (created for API docs)',
                    discount_amounts: [],
                    discountable: true,
                    discounts: [],
                    invoice_item: 'ii_1JUovyHPCO7LDipnIHa2G1sQ',
                    livemode: false,
                    metadata: {},
                    period: {
                        end: 1630485398,
                        start: 1630485398,
                    },
                    price: {
                        id: 'price_HKLSqChThppbgL',
                        object: 'price',
                        active: true,
                        billing_scheme: 'per_unit',
                        created: 1590176565,
                        currency: 'pln',
                        livemode: false,
                        lookup_key: null,
                        metadata: {},
                        nickname: null,
                        product: 'prod_HKLSEpcCj3zVvp',
                        recurring: null,
                        tax_behavior: 'unspecified',
                        tiers_mode: null,
                        transform_quantity: null,
                        type: 'one_time',
                        unit_amount: 1000,
                        unit_amount_decimal: '1000',
                    },
                    proration: false,
                    quantity: 1,
                    subscription: null,
                    tax_amounts: [],
                    tax_rates: [],
                    type: 'invoiceitem',
                },
            ],
            has_more: false,
            url: '/v1/invoices/in_1JUovyHPCO7LDipnKr5tYfV0/lines',
        },
        livemode: false,
        metadata: {},
        next_payment_attempt: 1630488998,
        number: '7BCB072F-DRAFT',
        on_behalf_of: null,
        paid: false,
        payment_intent: null,
        payment_settings: {
            payment_method_options: null,
            payment_method_types: null,
        },
        period_end: 1630485398,
        period_start: 1630485398,
        post_payment_credit_notes_amount: 0,
        pre_payment_credit_notes_amount: 0,
        quote: null,
        receipt_number: null,
        starting_balance: 0,
        statement_descriptor: null,
        status: 'draft',
        status_transitions: {
            finalized_at: null,
            marked_uncollectible_at: null,
            paid_at: null,
            voided_at: null,
        },
        subscription: 'sub_K9CNrlGYSi1sSC',
        subtotal: 1000,
        tax: null,
        total: 1000,
        total_discount_amounts: [],
        total_tax_amounts: [],
        transfer_data: null,
        webhooks_delivered_at: null,
    },
};
